# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1

  - package-ecosystem: docker
    directory: "/oauth-sheriff-quarkus-parent/oauth-sheriff-quarkus-integration-tests"
    schedule:
      interval: "weekly"
    # Note: This tracks Dockerfiles only. For docker-compose.yml images,
    # manual updates are required as dependabot's Docker ecosystem
    # doesn't scan compose files. Current versions in docker-compose.yml:
    # - quay.io/keycloak/keycloak:26.4.0
    # - prom/prometheus:v3.6.0
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1

  - package-ecosystem: npm
    directory: "/oauth-sheriff-quarkus-parent/oauth-sheriff-quarkus-deployment"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1
